//! Default embedded job registration via link-time [`inventory`] collection.

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use chronon_core::{Job, ScheduleKind};
use valence::Valence;

use crate::coordinator_trait::ChrononCoordinatorBackend;

/// Whether `existing` matches the schedule fields of `desired` (for default-job drift detection).
pub fn default_job_schedule_equivalent(existing: &Job, desired: &Job) -> bool {
    if existing.schedule_kind != desired.schedule_kind {
        return false;
    }
    match &desired.schedule_kind {
        ScheduleKind::Cron => {
            existing.cron_expr == desired.cron_expr && existing.timezone == desired.timezone
        }
        ScheduleKind::Manual => true,
        ScheduleKind::RunOnce => existing.run_once_at == desired.run_once_at,
    }
}

/// Copy schedule-related fields from `desired` onto `existing`, preserving `job_id` and identity.
pub fn merge_default_job_schedule_fields(mut existing: Job, desired: &Job) -> Job {
    existing.schedule_kind = desired.schedule_kind.clone();
    existing.cron_expr.clone_from(&desired.cron_expr);
    existing.timezone.clone_from(&desired.timezone);
    existing.next_run_at = desired.next_run_at;
    existing.run_once_at = desired.run_once_at;
    existing.run_once_claimed_at = desired.run_once_claimed_at;
    existing
        .run_once_claimed_by
        .clone_from(&desired.run_once_claimed_by);
    existing.run_once_completed_at = desired.run_once_completed_at;
    existing.run_once_claim_expires_at = desired.run_once_claim_expires_at;
    existing
}

/// Registers or no-ops the default job row (`get_job_by_name` then `add`).
pub type DefaultJobEnsureFn = fn(
    Arc<dyn ChrononCoordinatorBackend>,
    Valence,
) -> Pin<Box<dyn Future<Output = anyhow::Result<()>> + Send>>;

/// Static descriptor for one default Chronon job (embedded / template wiring).
#[derive(Debug)]
pub struct DefaultJobDescriptor {
    /// Stable job name (unique), used as registry key.
    pub job_name: &'static str,
    /// Idempotent ensure logic.
    pub ensure: DefaultJobEnsureFn,
}

crate::inventory::collect!(DefaultJobDescriptor);

impl quark::Registrable for DefaultJobDescriptor {
    fn registry_key(&self) -> &str {
        self.job_name
    }
}

/// Quark registry generated by `define_registry!` (methods inherit missing docs from the macro).
#[allow(missing_docs)]
mod default_job_registry {
    use super::DefaultJobDescriptor;

    quark::define_registry! {
        /// All default job descriptors from `#[chronon_macros_valence::script(..., default_job(...))]`
        /// and manual `submit!`.
        pub struct DefaultJobRegistry for DefaultJobDescriptor;
    }
}

pub use default_job_registry::DefaultJobRegistry;

impl DefaultJobRegistry {
    /// Job names in sorted order for deterministic registration across platforms.
    pub fn sorted_job_names(&self) -> Vec<&str> {
        let mut names = self.list();
        names.sort_unstable();
        names
    }
}

/// Ensure every discovered default job exists (idempotent).
///
/// Iterates [`DefaultJobRegistry`] in sorted name order and calls each descriptor's
/// [`DefaultJobEnsureFn`], building a fresh [`Valence`] per job via `build_valence`. Safe to call
/// on every boot: existing rows are updated in place when a default job's schedule drifts from
/// its current attributes (see [`default_job_schedule_equivalent`] /
/// [`merge_default_job_schedule_fields`], used internally by generated ensure functions).
///
/// # Examples
///
/// ```rust,ignore
/// use std::sync::Arc;
///
/// use chronon_coordinator::{ensure_default_jobs_embedded, ChrononCoordinatorBackend};
///
/// # async fn boot(
/// #     backend: Arc<dyn ChrononCoordinatorBackend>,
/// #     build_valence: impl FnMut() -> anyhow::Result<valence::Valence>,
/// # ) -> anyhow::Result<()> {
/// ensure_default_jobs_embedded(backend, build_valence).await?;
/// # Ok(())
/// # }
/// ```
pub async fn ensure_default_jobs_embedded(
    backend: Arc<dyn ChrononCoordinatorBackend>,
    build_valence: impl FnMut() -> anyhow::Result<Valence>,
) -> anyhow::Result<()> {
    ensure_default_jobs_embedded_with_skip(backend, build_valence, &[]).await
}

/// Like [`ensure_default_jobs_embedded`], but skips any job whose name appears in `skip`.
pub async fn ensure_default_jobs_embedded_with_skip(
    backend: Arc<dyn ChrononCoordinatorBackend>,
    mut build_valence: impl FnMut() -> anyhow::Result<Valence>,
    skip: &[&str],
) -> anyhow::Result<()> {
    let registry = DefaultJobRegistry::auto_discover();
    let names = registry.sorted_job_names();
    for job_name in &names {
        if skip.contains(job_name) {
            log::info!(
                target: "chronon_default_jobs",
                "Skipping default Chronon job `{job_name}` (split-runtime host policy)"
            );
            continue;
        }
        let Some(desc) = registry.get(job_name) else {
            continue;
        };
        log::info!(
            target: "chronon_default_jobs",
            "Ensuring default Chronon job `{}`",
            desc.job_name
        );
        let valence = build_valence()?;
        (desc.ensure)(backend.clone(), valence).await?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use chrono::{TimeZone, Utc};

    use super::*;

    fn cron_job(expr: &str, tz: Option<&str>) -> Job {
        let mut job = Job::new("probe", "probe_script");
        job.schedule_kind = ScheduleKind::Cron;
        job.cron_expr = Some(expr.to_string());
        job.timezone = tz.map(str::to_string);
        job
    }

    #[test]
    fn default_job_schedule_equivalent_detects_cron_drift() {
        let existing = cron_job("0 */1 * * * *", None);
        let desired = cron_job("*/10 * * * * *", None);
        assert!(!default_job_schedule_equivalent(&existing, &desired));

        let jid = existing.job_id.clone();
        let merged = merge_default_job_schedule_fields(existing, &desired);
        assert_eq!(merged.job_id, jid);
        assert_eq!(merged.cron_expr.as_deref(), Some("*/10 * * * * *"));
    }

    #[test]
    fn default_job_schedule_equivalent_cron_timezone_drift() {
        let existing = cron_job("0 0 * * * *", Some("UTC"));
        let desired = cron_job("0 0 * * * *", Some("America/New_York"));
        assert!(!default_job_schedule_equivalent(&existing, &desired));
    }

    #[test]
    fn default_job_schedule_equivalent_manual_always_matches() {
        let mut existing = Job::new("manual", "s");
        existing.schedule_kind = ScheduleKind::Manual;
        let mut desired = Job::new("manual", "s");
        desired.schedule_kind = ScheduleKind::Manual;
        desired.cron_expr = Some("ignored".into());
        assert!(default_job_schedule_equivalent(&existing, &desired));
    }

    #[test]
    fn default_job_schedule_equivalent_run_once_compares_instant() {
        let at = Utc.with_ymd_and_hms(2030, 1, 1, 0, 0, 0).unwrap();
        let mut existing = Job::new("once", "s");
        existing.schedule_kind = ScheduleKind::RunOnce;
        existing.run_once_at = Some(at);
        let mut desired = existing.clone();
        assert!(default_job_schedule_equivalent(&existing, &desired));
        desired.run_once_at = Some(at + chrono::Duration::hours(1));
        assert!(!default_job_schedule_equivalent(&existing, &desired));
    }

    #[test]
    fn default_job_schedule_equivalent_kind_mismatch() {
        let mut existing = Job::new("k", "s");
        existing.schedule_kind = ScheduleKind::Manual;
        let mut desired = Job::new("k", "s");
        desired.schedule_kind = ScheduleKind::Cron;
        desired.cron_expr = Some("0 * * * * *".into());
        assert!(!default_job_schedule_equivalent(&existing, &desired));
    }

    #[tokio::test]
    async fn ensure_default_jobs_embedded_noop_when_inventory_empty() {
        // Library unit-test binary has no `DefaultJobDescriptor` submit!.
        let backend: Arc<dyn ChrononCoordinatorBackend> = Arc::new(EmptyBackend);
        ensure_default_jobs_embedded(backend, || {
            panic!("build_valence must not run with empty inventory")
        })
        .await
        .expect("empty inventory is Ok");
    }

    /// Backend stub that panics if any mutating coordinator method is called.
    struct EmptyBackend;

    #[async_trait::async_trait]
    impl ChrononCoordinatorBackend for EmptyBackend {
        async fn load_jobs_from_db(&self) -> chronon_core::Result<()> {
            Ok(())
        }
        async fn upsert_job(&self, _job: Job) -> chronon_core::Result<()> {
            panic!("upsert")
        }
        async fn upsert_job_with_valence(
            &self,
            _valence: &Valence,
            _job: Job,
        ) -> chronon_core::Result<()> {
            panic!("upsert_with_valence")
        }
        async fn get_job(&self, _job_id: &str) -> Option<Job> {
            None
        }
        async fn get_job_by_name(&self, _job_name: &str) -> Option<Job> {
            None
        }
        async fn list_jobs(&self) -> Vec<Job> {
            vec![]
        }
        async fn list_runs(
            &self,
            _job_id: Option<&str>,
            _status: Option<&str>,
            _offset: usize,
            _limit: usize,
        ) -> chronon_core::Result<Vec<chronon_core::Run>> {
            Ok(vec![])
        }
        async fn get_run(&self, _run_id: &str) -> chronon_core::Result<Option<chronon_core::Run>> {
            Ok(None)
        }
        async fn pause_job(&self, _job_id: &str) -> chronon_core::Result<()> {
            Ok(())
        }
        async fn resume_job(&self, _job_id: &str) -> chronon_core::Result<()> {
            Ok(())
        }
        async fn list_revisions(
            &self,
            _job_id_or_name: &str,
        ) -> chronon_core::Result<Vec<chronon_core::JobRevision>> {
            Ok(vec![])
        }
        async fn update_job_config(
            &self,
            _job_id: &str,
            _updated: Job,
        ) -> chronon_core::Result<()> {
            panic!("update")
        }
        async fn update_job_config_with_valence(
            &self,
            _valence: &Valence,
            _job_id: &str,
            _updated: Job,
        ) -> chronon_core::Result<()> {
            panic!("update_with_valence")
        }
        async fn run_now(&self, _job_id: &str) -> chronon_core::Result<String> {
            panic!("run_now")
        }
        async fn run_now_with_params(
            &self,
            _job_id: &str,
            _params_override: Option<serde_json::Value>,
        ) -> chronon_core::Result<String> {
            panic!("run_now_with_params")
        }
    }
}
